algoritmo "exercicio tabuada 1"
// Função :
// Autor :  Marina Oliveira e Rebeka Lima
// Data : 16/03/2023
// Seção de Declarações 
var
    num,result:real
    i:inteiro
inicio
// Seção de Comandos
 escreva("Digite um número:")
 leia(num)
     i:=0
     enquanto (i<=10) faca
        result:= num*i
        escreval(num,"x",i,"=", result)
        i:=i+1
     fimenquanto
fimalgoritmo
